[package]
name = "fiatluz-c"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
name = "fiatluz"
crate-type = ["staticlib"]

[build-dependencies]
cbindgen = "0.27"

[dependencies]
fiatluz = { path = "./fiatluz" }
